#!/usr/bin/env ruby
require 'rubygems'
require 'json'
require 'uri'

DIR = ARGV[0] || 'words'

def naturalize(str)
	str.scan(/[^\d\.]+|[\d\.]+/).collect { |f| f.match(/\d+(\.\d+)?/) ? f.to_f : f }
end

def split_filename(filename)
	filename.sub(/^#{Regexp.escape DIR}\//, '').split('/', 2)
end

files = `find -L "#{DIR}" -name '*.m4a'`.split("\n").map{ |x| x.sub(/^.\//, '') }
files.sort! do |a, b|
	naturalize(a) <=> naturalize(b)
end
groups = files.group_by do |filename|
	split_filename(filename)[0]
end

result = []
groups.each_pair do |list_name, filenames|
	words = filenames.map do |filename|
		{ :text => split_filename(filename)[1].sub(/\.m4a$/, ''),
		  :url => URI.escape(filename).gsub('?', '%3F')
		}
	end
	result << {
		:name => list_name,
		:words => words
	}
end

puts "// Generated by index_data.rb"
puts "window.wordLists = #{result.to_json};"
